DL-7585 Modified AddDetailsView
hmrc/cest-frontend pull request #541
Opened 2023-01-25 16:13 UTC by rajanimohan22

# JIRA Story DL-7585 -Upgrade views to Govuk frontend

New feature

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist

 - [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2023-01-26 16:20 UTC, benryan1790 requested changes

2023-01-26 16:20 UTC, benryan1790 commented on app/views/AddDetailsView.scala.html
> +        @heading("addDetails.heading")
Can we use the headingNew component here as it contains the correct classes while the heading component uses the old play-ui classes

2023-01-26 16:20 UTC, benryan1790 commented on app/views/components/input_text_new.scala.html
> +        inline: Boolean = false,
the inline is not needed as the `govuk-radios--inline` class relates specifically to radio button inputs

2023-01-26 16:20 UTC, benryan1790 commented on app/views/components/input_textarea_new.scala.html
> +* Copyright 2023 HM Revenue & Customs
Please delete the duplicated copyright notice. If you delete both and then recompile it should generate the notice for you.

2023-01-26 17:06 UTC, rajanimohan22 commented on app/views/AddDetailsView.scala.html
> +        @heading("addDetails.heading")
Done

2023-01-27 09:52 UTC, benryan1790 approved these changes

2023-01-27 09:56 UTC, merged